<?xml version="1.0"  encoding="utf-8"?>
<!DOCTYPE customers[<!ELEMENT customers (customer,customer,customer,customer,customer,customer)>
									<!ELEMENT customer (#PCDATA)>
											<!ATTLIST customer name (tom | alexlee | jack) #REQUIRED>
									]>
<customers>
	<customer name="tom">1.1</customer>
	<customer name="alexlee">1.2</customer>
	<customer name="tom">1.3</customer>
	<customer name="jack">1.4</customer>
	<customer name="alexlee">1.5</customer>
	<customer name="jack">1.6</customer>
</customers>
