<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE  employees [<!ELEMENT employees (company,name,age,depName,salary,gender)>
										<!ELEMENT company (#PCDATA)>
												<!ATTLIST company id CDATA #REQUIRED>
										<!ELEMENT name (#PCDATA)>
												<!ATTLIST name Name CDATA  #IMPLIED >
										<!ELEMENT age (#PCDATA)>
												<!ATTLIST age Age  CDATA  "20">						
										<!ELEMENT depName (#PCDATA)>
												<!ATTLIST depName dn ( 市场部 | 教学部 | 教学管理部 ) #REQUIRED>
										<!ELEMENT salary (#PCDATA)>
												<!ATTLIST salary s CDATA "2000">
										<!ELEMENT gender (#PCDATA)>
												<!ATTLIST gender g  CDATA  #FIXED "male">
								]>
<employees>								
	<company id=""></company>
	<name Name=""></name>	
	<age  Age=""></age>
	<depName dn="教学部 "></depName>
	<salary s="2000"></salary>
	<gender g="male"></gender>
</employees>
